# Generated by Django 6.0.4 on 2026-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usersession_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, help_text="Video duration in format like '15:30'", max_length=20, null=True),
        ),
    ]
