# Generated by Django 5.2.8 on 2026-03-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
