# Generated by Django 5.2.8 on 2026-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmapp', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
