# Generated by Django 6.0.4 on 2026-04-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mark1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mark2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='mark3',
            field=models.IntegerField(default=0),
        ),
    ]
