# Generated by Django 6.0.4 on 2026-04-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_mark1_student_mark2_student_mark3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mark1',
            new_name='marka',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mark2',
            new_name='markb',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mark3',
            new_name='markc',
        ),
    ]
